[package]
name = "charlie"
version = "0.1.0"
authors = ["René Räisänen <rene.raisanen@knowit.no>"]
edition = "2018"

[dependencies]

[lib]
name = "2019_wasm_workshop_charlie"
path = "src/charlie.rs"
crate-type = ['cdylib']
